# Generated by Django 2.1.5 on 2019-01-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iuran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_penerimaan', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nilai_iuran', models.DecimalField(decimal_places=2, max_digits=20)),
                ('denda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('npp', models.CharField(max_length=8)),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('kode_perusahaan', models.CharField(max_length=20)),
                ('kode_divisi', models.CharField(max_length=3)),
                ('channel', models.CharField(max_length=7)),
                ('kode_penerimaan', models.CharField(max_length=20)),
                ('tgl_bayar', models.DateField()),
                ('kode_pembina', models.CharField(max_length=8)),
            ],
        ),
    ]
