# Generated by Django 2.1.5 on 2019-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemasaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pegawai', models.CharField(blank=True, max_length=32, null=True)),
                ('nama_tk', models.CharField(max_length=64)),
                ('tgl_kepesertaan', models.DateField()),
                ('kpj', models.CharField(max_length=8)),
                ('tgl_lahir', models.DateField()),
                ('npp', models.CharField(max_length=8)),
                ('kode_pembina', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tk',
            unique_together={('kpj', 'npp', 'tgl_kepesertaan')},
        ),
    ]
