# Generated by Django 2.1.5 on 2019-04-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemasaran', '0002_auto_20190424_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tk',
            name='kpj',
            field=models.CharField(max_length=11),
        ),
    ]
