# Generated by Django 2.1.5 on 2019-05-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemasaran', '0003_auto_20190424_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Npp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npp', models.CharField(max_length=8)),
                ('kode_divisi', models.CharField(max_length=3)),
                ('kode_perusahaan', models.CharField(max_length=20)),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('keps_awal', models.DateField()),
                ('kode_paket', models.CharField(default='2P', max_length=2)),
                ('kode_ilo', models.CharField(default='0', max_length=4)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_kontak', models.CharField(blank=True, max_length=200, null=True)),
                ('handphone_kontak', models.CharField(blank=True, max_length=15, null=True)),
                ('email_kontak', models.EmailField(blank=True, max_length=254, null=True)),
                ('kode_pembina', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='npp',
            unique_together={('npp', 'kode_divisi')},
        ),
    ]
