# Generated by Django 2.1.5 on 2019-06-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemasaran', '0004_auto_20190513_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='npp',
            name='blth_na',
            field=models.DateField(null=True),
        ),
    ]
